name: Access Id workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  ACCESS_ID: "scaler-123"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variable
        run: echo "The ACCESS_ID is : $ACCESS_ID"
  
  
