name: Python Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/setup-python@v4
          with:
            python-version: '3.9' 
        - name: Check Python3 version
          run: python3 --version
        - name: Upgrade Pip and Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest flake8

        - name: Verify Python Version
          run: python --version

        - name: Verify Flake8 Installation
          run: flake8 --version

        - name: Verify Pytest Installation
          run: pytest --version

        # - name: Run Linting with Flake8
        #   run: flake8 .

        # - name: Run Tests with Pytest
        #   run: pytest
