name: Use Secret in Workflow

on:
  push:  # Runs on every push
  workflow_dispatch:

jobs:
  use_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Test API Connectivity
        run: curl -I https://www.google.com

      - name: Test Public API
        run: curl -s https://ipinfo.io  # Removed verbose logging
      
      - name: Test GitHub API with Secret
        run: |
          echo "Authenticating to GitHub API..."
          RESPONSE=$(curl -H "Authorization: token ${{ secrets.GH_API_KEY }}" -s https://api.github.com/user)
          echo "GitHub API Response Received"
          
          # Print only non-sensitive info
          echo "$RESPONSE" | jq '.login'
