name: Use Secret in Workflow

on:
  push:  # Runs on every push
  workflow_dispatch:

jobs:
  use_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Test API Connectivity
        run: curl -I https://www.google.com


      - name: Authenticate to Third-Party API (Securely)
        run: |
          echo "Authenticating to API..."
          RESPONSE=$(curl -s -H "Authorization: Bearer $API_KEY" -X GET "https://secure-api.example.com/data")
          echo "API Response received successfully."
        env:
          API_KEY: ${{ secrets.API_KEY }}
