name: Use Secret in Workflow

on:
  push:  # Runs on every push

jobs:
  use_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Secret for API Authentication
        run: |
          echo "Authenticating to API..."
          curl -H "Authorization: Bearer $API_KEY" -X GET https://api.example.com/protected-resource
        env:
          API_KEY: ${{ secrets.API_KEY }}
