name: Secret Workflow

on:
  workflow_dispatch:
  push:
  # push:  # Trigger workflow on every push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print GitHub Secret
        run: echo "The Secret is $MYSECRET"
        env:
          MYSECRET: ${{ secrets.SECRET }}
